version: '3'
services:
  server:
    container_name: wheel-server
    build: .
    ports:
      - 1102:1102
    links:
      - mongo
  dashboard:
    container_name: wheel-dashboard
    build: .
    ports:
      - 1101:1101
    links:
      - server
  mongo:
    container_name: wheel-mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
