version: '3'
services:
  mongo:
    container_name: wheel-mongo
    image: mongo
    ports:
      - 27017:27017
  server:
      container_name: wheel-server
      build: ./server
      ports:
        - 1102:1102
      links:
        - mongo
  dashboard:
    container_name: wheel-dashboard
    build: ./dashboard
    ports:
      - 80:80
    depends_on:
      - server
